### ISSUE TITLE
ToDO: Find a way to highlight Tremor Totem

### ISSUE THREAD

**Issue by Evolvee** [Evolvee/EvolvePWPUI#11]
yep, fuck tremor

**Comment by Evolvee** [comment]
http://www.arenajunkies.com/topic/94767-addon-tremor-totem-solution/

**Comment by Evolvee** [comment]
http://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-guides/293393-solution-lamest-way-stop-tremors-any-totem.html

http://arena-tournament.com/forum/viewtopic.php?f=14&t=14651&sid=c40044eb2fc817a1f0b8147d62431765&start=15

**Comment by Evolvee** [comment]
disabled nameplates on all other totems, now i need to figure out how to click through their nameplates without selecting them

++ castbar on searing totem is still visible (when u target searing totem), lf some way to disable it or maybe just disable the auto-select when it start casting the spell on me when I have no target selected

**Comment by Evolvee** [comment]
code:  http://pastebin.com/s3dgwjeh
frame:EnableMouse(false) doesnt work

**Comment by Shanghi** [comment]
It would be dangerous! You wouldn't be able to change it while in combat (or else someone could make a stack of buttons and change which one is enabled for a bot), and old nameplates that were changed out of combat can be used again on new ones and be stuck with the wrong mouse setting! I haven't tried changing them yet, but would you still want to even with all that chaos?

**Comment by Evolvee** [comment]
oh thats scarry, what u mean by not being able to change while in combat? like if shaman spam totems, the newer ones  could be bugged? I mean... its still probably better if it works only sometimes than never :D 

atm, its working only visually... tremor is the only one with enabled nameplate over its body + the little searing totem castbar bug while targeting it
I hope its safe to use it now.

**Comment by Shanghi** [comment]
If you're in combat you just wouldn't be able to change the EnableMouse() thing. Any time a nameplate is shown again (a new totem made or by you just going out of range and then back) there's a chance it will reuse an old frame and that old frame might be using the wrong mouse clicking setting. That could cause an unpredictable moment of confusion when you try to click on something dangerous but it's using the click through setting so you have to quickly try to find the actual totem/person instead but it's too late now and the match is over!

Hiding/showing things like it does now is safe even in combat.

**Comment by Evolvee** [comment]
Oh ye i see, well then I will leave it as it is now . Its very good already, this was just a minor-prio suggestion since im attacking totems by clicking on their nameplates and not on their bodies(which could result in clicking on invisible nameplate of other totem) anyway. Thanks for reply!

Btw is that searing totem-nameplate castbar when searing is targeted fixable? (so there wont be additional "bar" in that space between tremor and players?
