### ISSUE TITLE
Random LUA error on login

### ISSUE THREAD

**Issue by Evolvee** [Evolvee/EvolvePWPUI#2]
caused by healthbar colouring script

**Comment by Shanghi** [comment]
Hello! This will probably stop that. Change:

```
hooksecurefunc("HealthBar_OnValueChanged", function(self)
        colour(self, self.unit)
end)
```

to:

```
hooksecurefunc("HealthBar_OnValueChanged", function()
        colour(this, this.unit)
end)
```

**Comment by Evolvee** [comment]
Thanks, seems like it works! i will test it properly today cuz i already fixed it few times but then i realized it bugs in certain situations.
