### ISSUE TITLE
random class portraits error

### ISSUE THREAD

**Issue by Evolvee** [Evolvee/EvolvePWPUI#21]
Error:  bad argument #1 to 'unpack' (table expected, got nil)
AddOn: ClassPortraits
File: ClassPortraits.lua
Line: 59
Count: 4

**Comment by Shanghi** [comment]
Change: `PartyMemberFrame1.portrait:SetTexCoord(unpack(p1));`
To: `if p1 then PartyMemberFrame1.portrait:SetTexCoord(unpack(p1)); end`

Change: `PartyMemberFrame2.portrait:SetTexCoord(unpack(p2));`
To: if p2 then PartyMemberFrame2.portrait:SetTexCoord(unpack(p2)); end

Change: PartyMemberFrame3.portrait:SetTexCoord(unpack(p3));
To: if p3 then PartyMemberFrame3.portrait:SetTexCoord(unpack(p3)); end

Change: PartyMemberFrame4.portrait:SetTexCoord(unpack(p4));
To: if p4 then PartyMemberFrame4.portrait:SetTexCoord(unpack(p4)); end

You can remove this part since party5 doesn't exist in TBC:

```
        if(UnitGUID("party5")~=nil and PartyMemberFrame5~=nil and PartyMemberFrame5.portrait~=nil) then
        PartyMemberFrame5.portrait:SetTexture(iconPath, true);
        local p5=classIcons[select(2, UnitClass("party5"))];
        PartyMemberFrame5.portrait:SetTexCoord(unpack(p5));
        end
```

**Comment by Evolvee** [comment]
tested it, new(same) error: 
Error:  bad argument #1 to 'unpack' (table expected, got nil)
AddOn: ClassPortraits
File: ClassPortraits.lua
Line: 101
Count: 2

**Comment by Shanghi** [comment]
Doomed! I'd have to see the new file. I just tried it and I'm not getting any other errors and the closest unpack() from line 101 I see is `texture:SetTexCoord(unpack(iconCoords))` but it shouldn't be possible for iconCoords to not exist there! If that is the line then UpdatePortrait() is probably used in a bad way somewhere.

**Comment by Evolvee** [comment]
oh ye sorry, my bad im not updating the UI atm cuz I will upload it all at once when its rdy. This is the current classportraits addon: http://www.megafileupload.com/7evd/ClassPortraits.zip

Btw this error didnt happen very often even before.

**Comment by Shanghi** [comment]
It's very mysterious! You could change UpdatePortrait() to this to make it safe and skip setting a messed up texture/unit:

```
local function UpdatePortrait(texture, unit)
   local _, class = UnitClass(unit)
   local iconCoords = CLASS_BUTTONS[class]
   if texture and iconCoords then
      texture:SetTexture(iconPath, true)
      texture:SetTexCoord(unpack(iconCoords))
   end
end
```

But the actual problem is still unknown! If you want to figure out what's causing it then a test error message like this would help if you can ever get it to happen again:

```
local function UpdatePortrait(texture, unit)
   local _, class = UnitClass(unit)
   local iconCoords = CLASS_BUTTONS[class]
   if texture and iconCoords then
      texture:SetTexture(iconPath, true)
      texture:SetTexCoord(unpack(iconCoords))
   else
      DEFAULT_CHAT_FRAME:AddMessage(format("ERROR! unit:[%s] class:[%s] texture:[%s]", (unit or "nil"), (class or "nil"), (texture and texture:GetName() or "unknown")), 1, 0, 0)
   end
end
```

**Comment by Evolvee** [comment]
Ok, i will test it with the 2nd code today, its happening once per 2+ hours of constant playing...

**Comment by Evolvee** [comment]
@Shanghi Seems like the error is gone, i will test it for 1 more week tho,

Btw sorry for abusing you... but your are the only one competent here :D --> u already helped me hiding the player status "glowing" texture, but is it possible to do that for focus/target? (https://github.com/Evolvee/EvolvePWPUI/issues/28) + this is interesting --> https://github.com/Evolvee/EvolvePWPUI/issues/11 , I already excluded tremor from all other totem  nameplates but im unable to somehow set its invisible nameplate to be clickable-through(when u click on it, u wont select it as a target)  Thx <3 :)

**Comment by Evolvee** [comment]
btw this just happened, i dont know why tho :/ never saw this before, something weird is hidden here:D
![wowscrnshot_073016_230352](https://cloud.githubusercontent.com/assets/1942409/17273275/66049cec-56af-11e6-8ff0-3795e1177d3e.jpg)

i think i somehow switched between players inspect in group, while fighting with training dummy

**Comment by Shanghi** [comment]
A grave mistake was made!

```
      hooksecurefunc("InspectFrame_OnEvent", function(event)
         if event == "UNIT_PORTRAIT_UPDATE" then
            UpdatePortrait(InspectFramePortrait, arg1)
         end
      end)
```

should be:

```
      hooksecurefunc("InspectFrame_OnEvent", function(event)
         if event == "UNIT_PORTRAIT_UPDATE" and InspectFrame.unit == arg1 then
            UpdatePortrait(InspectFramePortrait, arg1)
         end
      end)
```

**Comment by Evolvee** [comment]
Ok, thanks :)
