### ISSUE TITLE
texturescript.lua "button" LUA error 

### ISSUE THREAD

**Issue by Evolvee** [Evolvee/EvolvePWPUI#23]
Error:  attempt to index local 'Button' (a nil value)
AddOn: TextureScript
File: TextureScript.lua
Line: 342
Count: Infinite

caused by code which removes the outline texture on action_bar_buttons and increase the scale of icon inside it

(code from woundmans UI btw)

**Comment by Evolvee** [comment]
associated with https://github.com/Evolvee/EvolvePWPUI/issues/1  dark outline texture fading when pressing spellbook/switching weps/items etc

**Comment by Shanghi** [comment]
I just looked at Blizzard's ActionButton_ShowGrid() and changing:

```
hooksecurefunc("ActionButton_ShowGrid", function(Button) _G[Button:GetName().."NormalTexture"]:SetVertexColor(1, 1, 1, 1) end)
```

to:

```
hooksecurefunc("ActionButton_ShowGrid", function(Button)
   if not Button then
      Button = this
   end
   _G[Button:GetName().."NormalTexture"]:SetVertexColor(1, 1, 1, 1)
end)
```

will probably/hopefully get rid of the errors when Button doesn't exist.

**Comment by Evolvee** [comment]
I will test it, thanks.

**Comment by Evolvee** [comment]
holy shit, seems like u just fixed the entire problem :D
