### ISSUE TITLE
Art frame stuck in a weird place

### ISSUE THREAD

**Issue by thraneloldk** [Evolvee/EvolvePWPUI#42]
![wowscrnshot_022317_191751](https://cloud.githubusercontent.com/assets/25982859/23272764/c99c1eba-f9fc-11e6-827e-6e92f6e0bbee.jpg)

I installed your UI today while testing a new TBC server using the 2.4.3  version og wow.

Everything seems fine but the art frame and i cant seem to move it/remove it?

**Comment by Evolvee** [comment]
Simply delete "kgPanels" addon + kgPanels config addon from your addon directory...  Its ugly as fuck, I will delete it in next release anyway... 
But if u rly want it to be on the side of the bars, try to copy paste saved variables of that and copy paste it to yours...
