### ISSUE TITLE
32 bit blp rgb+a guide

### ISSUE THREAD

**Issue by v0dkuh** [Evolvee/EvolvePWPUI#45]
Can we please get a guide on how to convert/make the correct image file types for custom portrait skins?

**Comment by Evolvee** [comment]
its in readme document inside the folder,
basically it needs to be 64x64 ( it could be maybe even bigger like 512x512) image in blp format(maybe even .tga would work) with alpha channel enabled

the best way to do that is to create this image in .png format and then convert it to .blp via http://www.wowinterface.com/downloads/info6127-BLP2PNG.html this program for example

the png needs to be RGB+Alpha format 32 bit format... im creating this in Adobe Affter Effects cuz I dont have Photoshop or any other similar program...

then all you need to do is to replace the current skin in the folder and rename it...

--

this is the exact same procedure as to any other images you want to replace in world of warcraft.. casting bars/textures etc...

**Comment by v0dkuh** [comment]
thanks! i was using a different conversion program that was messing up the formatting or compression somehow, that one works perfect though
