### ISSUE TITLE
offtopic :D

### ISSUE THREAD

**Issue by Evolvee** [Evolvee/EvolvePWPUI#6]
Currently the default characters head is there.

**Comment by Evolvee** [comment]
PaperDoll textures / PaperDoll xml/lua files

**Comment by Shanghi** [comment]
Someone wanted this a while ago on the corecraft forum! You can add this to ClassPortraits.lua, but will have to change UpdatePortrait() to handle your custom player portraits if the unit is "player"

```
local function UpdatePortrait(texture, unit)
   local _, class = UnitClass(unit)
   local iconCoords = CLASS_BUTTONS[class]
   texture:SetTexture(iconPath, true)
   texture:SetTexCoord(unpack(iconCoords))
end

-- character sheet frame
hooksecurefunc("CharacterFrame_OnShow", function()
   UpdatePortrait(CharacterFramePortrait, "player")
end)
hooksecurefunc("CharacterFrame_OnEvent", function(event)
   if event == "UNIT_PORTRAIT_UPDATE" then
      UpdatePortrait(CharacterFramePortrait, "player")
   end
end)

local addonLoadEvent = CreateFrame("frame")
addonLoadEvent:RegisterEvent("ADDON_LOADED")
addonLoadEvent:SetScript("OnEvent", function(self, e, addon)
   -- talent frame
   if addon == "Blizzard_TalentUI" then
      hooksecurefunc(PlayerTalentFrame, "updateFunction", function()
         UpdatePortrait(PlayerTalentFramePortrait, PlayerTalentFrame.unit or "player")
      end)
      hooksecurefunc("PlayerTalentFrame_OnEvent", function()
         if event == "UNIT_PORTRAIT_UPDATE" and UnitIsUnit(arg1, "player") then
            UpdatePortrait(PlayerTalentFramePortrait, "player")
         end
      end)
      return
   end
   -- inspect frame
   if addon == "Blizzard_InspectUI" then
      hooksecurefunc("InspectFrame_OnShow", function()
         UpdatePortrait(InspectFramePortrait, InspectFrame.unit)
      end)
      hooksecurefunc("InspectFrame_UnitChanged", function()
         UpdatePortrait(InspectFramePortrait, InspectFrame.unit)
      end)
      hooksecurefunc("InspectFrame_OnEvent", function(event)
         if event == "UNIT_PORTRAIT_UPDATE" then
            UpdatePortrait(InspectFramePortrait, arg1)
         end
      end)
      return
   end
end)
```

**Comment by Evolvee** [comment]
Thanks! i will try to update it for additional tabs: spellbook, quest log, friendslist/social, LFG. Btw im sorry that im writing it here but.. :D do u know something about this? http://pastebin.com/ZtK1HXnJ
It changes health status bar on target/nameplates etc to go down smoothly when you hit them. That means there is a small animation between current HP and previous HP which results in a smooth HP bar. It works but the only problem is this: Whenever i hit something, their HPs are for a second totally retarded --> http://i.imgur.com/5TlWkxD.jpg  and then it gets to current HP value but whenever i hit again, it makes the same shit.
I found 2 similar addons which do that: http://pastebin.com/QTwZA6Jj , http://pastebin.com/vjKQxWAN

**Comment by Shanghi** [comment]
At the top put this (to make it a bit faster since it's used so much):
`local floor = math.floor`

Then change:
`bar:SetValue_(new)`
to:
`bar:SetValue_(floor(new))`

Then it should count up/down with whole numbers instead of 932.28347829429864278523574846827346283468236582634!

**Comment by Evolvee** [comment]
Nice!, just a small adjustment: is it possible to leave the "text" in default state(showing current not-animated value) and animate only the HP status bar? I mean its kinda distracting when there are tons of numbers rolling 24/7... 
And btw there is a small bug, not anything major, but when u sometimes target random npc/player, their HP bar is going up from nothing(instead of being full when u target them), same for when you open reputation tab and scroll up and down ...

**Comment by Shanghi** [comment]
I agree!

   Change:

```
   local function SmoothSetValue(self, value)
      local _, max = self:GetMinMaxValues()
```

   to:

```
   local function SmoothSetValue(self, value)
      self.finalValue = value
      local _, max = self:GetMinMaxValues()
```

   then in TextureScript.lua, change:
   `local value = textStatusBar:GetValue();`
   to:
   `local value = textStatusBar.finalValue or textStatusBar:GetValue();`

I'm not sure if every type of bar will go through that though! Hopefully they do.

It's unrelated but \EvolvePWPUI\Interface\Addons\Essential Core\ClassPortraits\SKINS\Gul´Dan.blp seems to be corrupted in the zip file, at least when trying to extract it with the newest 7zip.

**Comment by Evolvee** [comment]
It says corrupted if ur trying to unzip only 1 file and you are too deep(in the zip directory) :D, or atleast winrar said that, but when i unziped whole folder it was working fine tho. I unziped it now, converted to PNG and its working for me. http://i.imgur.com/lfnoLHO.png
Its honestly bad packed, i will use default windows .zip next time (i had sum errors with git files so i just packed it in .rar to prevent that :D)

**Comment by Evolvee** [comment]
The status bar text is fixed! The second problem is still there. Im trying it in OG by targeting random ppl. It happens when u login/reload ui on playerframe/target and then +- 2-3 times and then it seems fixed...

**Comment by Shanghi** [comment]
I think it's just the ´ character and each zip handler handles unicode names differently! The default Windows one extracted it but changed ´ to the letter n. If you change ´ to a simple ' then it will probably be fine for everyone everywhere with no chance for an error that terrifies them.

I'm not sure what the 2nd problem was! Is it how it shows an animation filling up the first time you target anyone, or is it something even worse? I'm trying to figure out how to stop it from doing the unwanted first animation now.

**Comment by Evolvee** [comment]
Yep that is... filling the full bar from 0 to 100% but it happens only once/twice... then its fine. Oh yea, i will rename it, that was dumb :D is it better now?

**Comment by Shanghi** [comment]
Normally it knows not to animate a new person's bar by seeing if their max health/something is different from the last amount set, but the very first time the bar is created there is no max set!

Changing:
`if value == self:GetValue() or self._max and self._max ~= max then`
to:
`if value == self:GetValue() or not self._max or self._max ~= max then`

will stop the first animation, but it will still do it if you switch targets between 2 things with the same maximum, like killing a scorpion with 198 health then targeting another one. I'm trying to think of a nicer way to handle it. Also, a dead thing will show a 0 over the Dead text!

The zip file worked!

**Comment by Shanghi** [comment]
Here's a way that uses their unique ID when possible and the max number for anything else!

Change the barstosmooth table at the top to include the unit type of each one. You could probably add the focus bar and whatever the party member targets are called too but I'm not sure if there's anything special about those!

```
local barstosmooth = {
   PlayerFrameHealthBar = "player",
   PlayerFrameManaBar = "player",
   TargetFrameHealthBar = "target",
   TargetFrameManaBar = "target",
   MainMenuExpBar = "",
   ReputationWatchStatusBar = "",
   PartyMemberFrame1HealthBar = "party1",
   PartyMemberFrame1ManaBar = "party1",
   PartyMemberFrame2HealthBar = "party2",
   PartyMemberFrame2ManaBar = "party2",
   PartyMemberFrame3HealthBar = "party3",
   PartyMemberFrame3ManaBar = "party3",
   PartyMemberFrame4HealthBar = "party4",
   PartyMemberFrame4ManaBar = "party4",
   ReputationBar1 = "",
   ReputationBar2 = "",
   ReputationBar3 = "",
   ReputationBar4 = "",
   ReputationBar5 = "",
   ReputationBar6 = "",
   ReputationBar7 = "",
   ReputationBar8 = "",
   ReputationBar9 = "",
   ReputationBar10 = "",
   ReputationBar11 = "",
   ReputationBar12 = "",
   ReputationBar13 = "",
   ReputationBar14 = "",
   ReputationBar15 = "",
   SkillRankFrame1 = "",
   SkillRankFrame2 = "",
   SkillRankFrame3 = "",
   SkillRankFrame4 = "",
   SkillRankFrame5 = "",
   SkillRankFrame6 = "",
   SkillRankFrame7 = "",
   SkillRankFrame8 = "",
   SkillRankFrame9 = "",
   SkillRankFrame10 = "",
   SkillRankFrame11 = "",
   SkillRankFrame12 = "",
 }
```

Change:
`for _, v in pairs (barstosmooth) do if v then SmoothBar(v) end end`
to:

```
   for k,v in pairs (barstosmooth) do
      if _G[k] then
         SmoothBar(_G[k])
         if v ~= "" then
            _G[k].unitType = v
         end
      end
   end
```

Then finally change the SmoothSetValue() function to:

```
local function SmoothSetValue(self, value)
   self.finalValue = value
   if self.unitType then
      local guid = UnitGUID(self.unitType)
      if value == self:GetValue() or not guid or guid ~= self.lastGuid then
         smoothing[self] = nil
         self:SetValue_(value)
      else
         smoothing[self] = value
      end
      self.lastGuid = guid
   else
     local _, max = self:GetMinMaxValues()
     if value == self:GetValue() or self._max and self._max ~= max then
         smoothing[self] = nil
         self:SetValue_(value)
     else
         smoothing[self] = value
     end
     self._max = max
   end
end
```

Edit 1: Also, the 0 over Dead thing might just be me because I was just using a single test lua file to try things and don't have the rest!

Edit 2: I just noticed that reputation bars in the character sheet place go crazy when you scroll through them since they all use the same max amount! Maybe those should be removed since I doubt anyone will be watching those specific bars when getting reputation!

Edit 3: The skills tab does that too! I was wondering what those SkillRankFrame ones were before! Those should probably be removed too since only buying mount riding will give enough to show a noticeable animation and I doubt they'll open that tab to see it!

Edit 4: You can add these to the class portraits file to show the player's icon in those other windows.

```
-- LFG, quest log, spellbook, and social window icons
LFGParentFrame:HookScript("OnShow", function() UpdatePortrait(LFGParentFrameIcon, "player") end)
UpdatePortrait((select(2, QuestLogFrame:GetRegions())), "player")
UpdatePortrait((SpellBookFrame:GetRegions()), "player")
UpdatePortrait((FriendsFrame:GetRegions()), "player")
```

Or if you want to use special icons for the quest log/spellbook/social window you can just set them directly since they never change:

```
select(2, QuestLogFrame:GetRegions()):SetTexture("Interface/Icons/Spell_Magic_PolymorphChicken")
SpellBookFrame:GetRegions():SetTexture("Interface/Icons/Spell_Magic_PolymorphChicken")
FriendsFrame:GetRegions():SetTexture("Interface/Icons/Spell_Magic_PolymorphChicken")
```

**Comment by Evolvee** [comment]
The 0 thingy doesnt happen to me however when i loot the dead scorpid, there is a little animation of HP status bar going down(to death) from like 30% HP. -->https://www.youtube.com/watch?v=lGSYV6LTNDY&feature=youtu.be
 Otherwise its perfect!
E: this is very minor u dont even have to bother with it, i dont expect this UI to be used in PVE.
Yep i will remove the reputation + skill bar.
E2: btw this issue might be caused server-side, L4G doesnt show the last hit dmg before death, i will try it on smolder but i think it will be the same.
E3: I used the 1st code for additional ClassPortraits frames cuz its icons are rounded, the 2nd code make the incons in square, there should probably be some function like SetPortraitToTexture to make it rounded.
E4: btw is there any way of also implementing this smoothing into nameplate bars? Schaka told me its possible only via another OnUpdate function, so i would rather just let it to be in default if its CPU-heavy. There is a lot of OnUpdate functions in this UI already. http://pastebin.com/wk23TtVY

**Comment by Shanghi** [comment]
Under `SmoothBar(_G[k])` add:
`_G[k]:SetScript("OnHide", function() this.lastGuid = nil; this.max_ = nil end)`
Since it just closes the target frame instead of setting the value to 0, when you target them again it starts from before the last hit like you said. It can also happen if you target someone, then no one, then they heal or something, then you look at them again. This will make the bar erase who it's tracking if it's closed.

The second icon way was in case you wanted to make your own textures to replace the ones like the spellbook. They just cheat with those textures by making the corners transparent like
![images](https://cloud.githubusercontent.com/assets/2672633/17084142/a985a54a-5184-11e6-9c17-4c02560e1e7b.jpg)

I'll have to investigate the nameplates since I haven't tried to do much with them yet! OnUpdate would certainly be needed to at least constantly look for them though. It has to do that forever since they're always changing so you can't just find them once to use them directly.

**Comment by Evolvee** [comment]
nice, thanks, i will probably just edit all the custom textures to have these alpha borders
E: the only small thing now is when u invite someone into party or when u enter/leave arena etc, but thats rly minor, doesnt even need to be fixed.

**Comment by Evolvee** [comment]
@Shanghi  Just an offtopic question... would it be possible to change healthbar color of Player at low HP? Lets say green HP bar, at 20% HP switches to red.
It should be possible with PlayerFrameHealthBar:SetStatusBarColor(0,1,0) right?

**Comment by Shanghi** [comment]
What did it do when they joined the group? Nothing special happened for me!

That's possible. In TextureScript.lua, you could replace colour() with this version. It changes the player's to red at 20 and yellow at 60 but you could change that part to be as simple or fancy as you want!

```
local function colour(statusbar, unit)
   if UnitIsPlayer(unit) and UnitIsConnected(unit) and unit == statusbar.unit then
      if statusbar == PlayerFrameHealthBar then
         local percent = UnitHealth(statusbar.unit) * 100 / UnitHealthMax(statusbar.unit)
         if percent <= 20 then
            statusbar:SetStatusBarColor(1, 0, 0)
         elseif percent <= 60 then
            statusbar:SetStatusBarColor(1, 1, 0)
         else
            statusbar:SetStatusBarColor(0, 1, 0)
         end
      else
         local _, class = UnitClass(unit)
         local c = CUSTOM_CLASS_COLORS and CUSTOM_CLASS_COLORS[class] or RAID_CLASS_COLORS[class]
         statusbar:SetStatusBarColor(c.r, c.g, c.b)
      end
   end
end
```

If you want your health to do that in other places (like if you target yourself), then change:
`if statusbar == PlayerFrameHealthBar then`
to:
`if UnitIsUnit(statusbar.unit, "player") then`

**Comment by Evolvee** [comment]
It animated the HP party bar from 80% to 100% but i tried it few times now and it seems fixed so nvm,

Nice! the bar si sooo sexy now.
Thanks :)

**Comment by Evolvee** [comment]
Error:  attempt to index local 'c' (a nil value)
AddOn: TextureScript
File: TextureScript.lua
Line: 88
Count: 4

:P

**Comment by Shanghi** [comment]
Some strange class must not have its color set in the CUSTOM_CLASS_COLORS or RAID_CLASS_COLORS tables (or they somehow don't have a class at all)! This will make it not try to color such strange creatures:
`statusbar:SetStatusBarColor(c.r, c.g, c.b)`
to:

```
if c then
   statusbar:SetStatusBarColor(c.r, c.g, c.b)
end
```

**Comment by Evolvee** [comment]
ok, thanks
